version: "3"
services:
  web_client:
    image: web_client
    build: ./client
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - web_server
    depends_on:
      - "web_server"
    networks:
      - webapp
  web_server:
    image: web_server
    build: ./server
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - "mongo"
      - "users_microservice"
      - "patient_microservice"
    networks:
      - webapp
  users_microservice:
    image: users_microservice
    build: ./microservices/users_microservice
    command: npm start
    ports:
      - "3002:3002"
    volumes:
      - ./microservices/users_microservice:/users_microservice
      - /users_microservice/node_modules
    depends_on:
      - "mongo"
    networks:
      - webapp
  patient_microservice:
    image: patient_microservice
    build: ./microservices/patient_microservice
    command: npm start
    ports:
      - "3003:3003"
    volumes:
      - ./microservices/patient_microservice:/patient_microservice
      - /patient_microservice/node_modules
    depends_on:
      - "mongo"
    networks:
      - webapp
  mongo:
    image: "mongo"
    command: mongod --noauth --smallfiles
    ports:
      - "27017:27017"
    networks:
      - webapp
networks:
  webapp:
    driver: bridge
