version: "3"
services:
  web_client:
    image: web_client
    build: ./client
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - web_server
    depends_on:
      - "web_server"
      - "web_server_two"
    networks:
      - webapp
  web_server:
    image: web_server
    build: microservices/user_service
    command: npm start
    ports:
      - "3010:3010"
    volumes:
      - ./user_service:/user_service
      - /user_service/node_modules
    depends_on:
      - "mongo"
    networks:
      - webapp
  web_server_two:
    image: web_server_two
    build: microservices/surveys_service
    command: npm start
    ports:
      - "3011:3011"
    volumes:
      - ./surveys_service:/server_two
      - /surveys_service/node_modules
    depends_on:
      - "mongo"
    networks:
      - webapp
  mongo:
    image: "mongo"
    command: mongod --noauth --smallfiles
    ports:
      - "27017:27017"
    networks:
      - webapp
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web_server
      - web_server_two
      - web_client
    networks:
      - webapp
networks:
  webapp:
    driver: bridge
