const USER_REGISTER = "USER_REGISTER";
const USER_LOGIN = "USER_LOGIN";
const CURRENT_USER = "CURRENT_USER";
const SURVEYS = "SURVEYS";

export const SURVEYS_FETCHING = `${SURVEYS}_FETCHING`;
export const SURVEYS_FETCHED = `${SURVEYS}_FETCHED`;
export const SURVEYS_ERROR = `${SURVEYS}_ERROR`;

export const SET_CURRENT_USER_FETCHING = `SET_${CURRENT_USER}_FETCHING`;
export const SET_CURRENT_USER_FETCHED = `SET_${CURRENT_USER}_FETCHED`;
export const SET_CURRENT_USER_NOTAUTH = `SET_${CURRENT_USER}_NOTAUTH`;

export const USER_REGISTER_FETCHING = `${USER_REGISTER}_FETCHING`;
export const USER_REGISTER_ERROR = `${USER_REGISTER}_ERROR`;
export const USER_REGISTER_FETCHED = `${USER_REGISTER}_FETCHED`;

export const USER_LOGIN_FETCHING = `${USER_LOGIN}_FETCHING`;
export const USER_LOGIN_ERROR = `${USER_LOGIN}_ERROR`;
export const USER_LOGIN_FETCHED = `${USER_LOGIN}_FETCHED`;
